# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: redirector
builds:
  - id: redirector-builds
    binary: redirector
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: ["amd64", "arm64"]
    flags: [-trimpath]
    ldflags: [-s, -w]
    dir: redirector
upx:
  - enabled: true
    ids: [redirector-builds]
    goos: [linux]
    compress: best
    lzma: true
archives:
  - id: redirector-archives
    builds: [redirector-builds]
    format: binary
    name_template: >-
      {{- .Binary }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .Mips }}-{{ . }}{{ end }}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
dockers:
  - ids: [redirector-builds]
    goos: linux
    goarch: amd64
    image_templates: ["ghcr.io/pidrakin/redirector:v{{ .Version }}-amd64"]
    dockerfile: Containerfile
    use: buildx
    build_flag_templates: ["--platform=linux/amd64"]
  - ids: [redirector-builds]
    goos: linux
    goarch: arm64
    image_templates: ["ghcr.io/pidrakin/redirector:v{{ .Version }}-arm64"]
    dockerfile: Containerfile
    use: buildx
    build_flag_templates: ["--platform=linux/arm64"]
docker_manifests:
  - name_template: ghcr.io/pidrakin/redirector:v{{ .Version }}
    image_templates:
      - ghcr.io/pidrakin/redirector:v{{ .Version }}-amd64
      - ghcr.io/pidrakin/redirector:v{{ .Version }}-arm64
release:
  mode: replace
announce:
  telegram:
    enabled: true
    chat_id: -1001510892782
    message_template: |
      redirector {{ mdv2escape .Tag }}

      Awesome new redirector version is out
      Check it out at {{ mdv2escape .ReleaseURL }}

      Or Pull the container:

      docker pull {{ mdv2escape "ghcr.io/pidrakin/redirector" }}:{{ mdv2escape .Tag }}
