repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
  - id: go-fmt
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-yaml
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace
